server:
  port: 8084
spring:
  application:
    name: dubbo-user
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: localhost:8848
        namespace: public
      config:
        contextPath: /nacos
dubbo:
  application:
    name: dubbo-user
  registry:
    address: nacos://localhost:8848
  protocol:
    port: 20881