server:
  port: 8083
spring:
  application:
    name: dubbo-order
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: localhost:8848
        namespace: public
      config:
        contextPath: /nacos
dubbo:
  application:
    name: dubbo-order
  registry:
    address: nacos://localhost:8848
  protocol:
    port: 20880